### ISSUE TITLE
Project doesn't build

### ISSUE THREAD

**Issue by isaacabraham** [bricelam/EFCore.FSharp#6] opened 2018-02-08 08:42 UTC
On checking out master, doing a `dotnet build` gives the following errors:

```
error MSB4184: The expression "registry:HKEY_LOCAL_MACHINE\SOFTWARE\Microsoft\Microsoft SDKs\Windows\v10.0@InstallationFolder" cannot be evaluated.
warning NU1503: Skipping restore for project 'C:\Users\Isaac\Source\Repos\EFCore.FSharp\EFCore.FSharp\EFCore.FSharp.fsproj'. The project file may be invalid or missing targets required for restore. [C:\Users\Isaac\Source\Repos\EFCore.FSharp\EFCore.FSharp.sln]
error MSB4184: The expression "registry:HKEY_LOCAL_MACHINE\SOFTWARE\Microsoft\Microsoft SDKs\Windows\v10.0@InstallationFolder" cannot be evaluated.

Restore completed in 46.54 ms for C:\Users\Isaac\Source\Repos\EFCore.FSharp\EFCore.FSharp.Test\EFCore.FSharp.Test.fsproj.

error MSB4184: The expression "registry:HKEY_LOCAL_MACHINE\SOFTWARE\Microsoft\Microsoft SDKs\Windows\v10.0@InstallationFolder" cannot be evaluated.
error MSB4184: The expression "registry:HKEY_LOCAL_MACHINE\SOFTWARE\Microsoft\Microsoft SDKs\Windows\v10.0@InstallationFolder" cannot be evaluated.
```

How can I fix this?

**Comment by simontaite** [comment] 2018-02-13 08:28
This appears to be caused by these lines in EFCore.FSharp.fsproj
```
<WindowsSdkDir Condition=" '$(WindowsSdkDir)' == '' ">$(registry:HKEY_LOCAL_MACHINE\SOFTWARE\Microsoft\Microsoft SDKs\Windows\v10.0@InstallationFolder)</WindowsSdkDir>
<WindowsSDKVersion Condition=" '$(WindowsSDKVersion)' == '' ">$(registry:HKEY_LOCAL_MACHINE\SOFTWARE\Microsoft\Microsoft SDKs\Windows\v10.0@ProductVersion)\</WindowsSDKVersion>
<SignToolCommand>"$(WindowsSdkDir)bin\$(WindowsSDKVersion)x86\signtool.exe" sign /t $(TimestampUrl) /q</SignToolCommand>
```

If you comment them out then it should build, although it will not be signed.
This issue also prevents `dotnet build` from running on any non-Windows platform

@bricelam We'll need to find a way to sign the package in a more cross-platform friendly manner

**Comment by bricelam** [comment] 2018-02-13 17:24
Yes, I intend to address this. It think it will be fixed in the next version of the SDK. To workaround it, just remove those properties.

By default, it won't sign anyway. Those are just there for me so I can sign it before publishing release to NuGet.org.

**Comment by isaacabraham** [comment] 2018-02-20 16:47
FYI, to get this to build **in VS 2017** I also had to remove the line:

``` xml
<AssemblyOriginatorKeyFile>key.snk</AssemblyOriginatorKeyFile>
```

This wasn't needed to get it to build from the cmdline, though.

**Comment by simontaite** [comment] 2018-03-05 11:38
This is preventing Appveyor and Travis builds

**Closed** 2018-03-05 17:28 UTC
